// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVFitbsxMuBo1LgOEOBGKXaeeJMW3K6o',
    appId: '1:931356474584:web:03eba6f9ef827b9ad7ebad',
    messagingSenderId: '931356474584',
    projectId: 'bladeya-45fa8',
    authDomain: 'bladeya-45fa8.firebaseapp.com',
    storageBucket: 'bladeya-45fa8.appspot.com',
    measurementId: 'G-KG27EZFKGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnPAXRd8dmVvV4gVCCYYf-oqrsEeUYtA',
    appId: '1:931356474584:android:a6a6f6323beefc09d7ebad',
    messagingSenderId: '931356474584',
    projectId: 'bladeya-45fa8',
    storageBucket: 'bladeya-45fa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJCBL0IO1MC2gtiAk3n7XN4HSJgZqE_pY',
    appId: '1:931356474584:ios:4ed59102e2aec89bd7ebad',
    messagingSenderId: '931356474584',
    projectId: 'bladeya-45fa8',
    storageBucket: 'bladeya-45fa8.appspot.com',
    iosBundleId: 'com.example.baldeya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJCBL0IO1MC2gtiAk3n7XN4HSJgZqE_pY',
    appId: '1:931356474584:ios:4ed59102e2aec89bd7ebad',
    messagingSenderId: '931356474584',
    projectId: 'bladeya-45fa8',
    storageBucket: 'bladeya-45fa8.appspot.com',
    iosBundleId: 'com.example.baldeya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsVFitbsxMuBo1LgOEOBGKXaeeJMW3K6o',
    appId: '1:931356474584:web:4d6a1ba9c4e1f955d7ebad',
    messagingSenderId: '931356474584',
    projectId: 'bladeya-45fa8',
    authDomain: 'bladeya-45fa8.firebaseapp.com',
    storageBucket: 'bladeya-45fa8.appspot.com',
    measurementId: 'G-35CBE3Z9MM',
  );
}
